apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  ports:
    - name: "http"
      port: 80
      targetPort: 80
      nodePort: {{ .Values.nginx.ports.nodePort }}
  selector:
    memorial.service: app-nginx
