apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: NodePort
  ports:
    - name: "http"
      port: 80
      targetPort: 80
      nodePort: 30007
  selector:
    memorial.service: nginx
