apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
    - name: "5432"
      port: {{ .Values.ports.postgres }}
      targetPort: {{ .Values.ports.postgres }}
  selector:
    memorial.service: postgres
