apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    memorial.service: postgres
  name: postgres
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      memorial.service: postgres
  template:
    metadata:
      labels:
        memorial.network/manifests-sail: "true"
        memorial.service: postgres
    spec:
      containers:
        - env:
            - name: PGPASSWORD
              value: "{{ .Values.postgres.env.PGPASSWORD }}"
            - name: POSTGRES_DB
              value: "{{ .Values.postgres.env.POSTGRES_DB }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.postgres.env.POSTGRES_PASSWORD }}"
            - name: POSTGRES_USER
              value: "{{ .Values.postgres.env.POSTGRES_USER }}"
            - name: PGDATA
              value: "{{ .Values.postgres.env.PGDATA }}"
          image: {{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}
          name: postgres
          ports:
            - containerPort: {{ .Values.postgres.ports.containerPort }}
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pgdata
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.postgres.pvc.storage }}
