ports:
  ingress: 80
  postgres: 5432
  nginx: 80
images:
  nginx:
    repository: ghcr.io/miso-memoreal/memorial-backend-nginx
    tag: main
  app:
    repository: ghcr.io/miso-memoreal/memorial-backend-php
    tag: main
  postgres:
    repository: postgis/postgis
    tag: 15-3.4
pvc:
  postgres: 100Mi
resources:
  app:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
hpa:
  app:
      minReplicas: 3
      maxReplicas: 20
      targetCPUUtilizationPercentage: 70
envs:
  nginx:
    WWWUSER: "1000"
  postgres:
    PGPASSWORD: password
    POSTGRES_DB: memorial_backend
    POSTGRES_PASSWORD: password
    POSTGRES_USER: memorial
    # HACK: non-emptyで死ぬので一階層掘る
    PGDATA: /var/lib/postgresql/data/postgres
  app:
    APP_KEY: base64:ORH8GelTP4n6hK5jANROtYkU3V0o43V+rM8BJOwII4Q=
    APP_URL_SCHEME: "https://"
    APP_URL_DOMAIN: "localhost:8080"
    APP_DEBUG: true
    APP_ENV: production
    APP_NAME: memoReal
    BROADCAST_DRIVER: log
    CACHE_DRIVER: file
    DB_CONNECTION: pgsql
    DB_DATABASE: memorial_backend
    DB_HOST: postgres
    DB_PASSWORD: password
    DB_PORT: 5432
    DB_USERNAME: memorial
    FILESYSTEM_DISK: local
    LARAVEL_SAIL: "1"
    LOG_CHANNEL: stack
    LOG_DEPRECATIONS_CHANNEL: stack
    LOG_LEVEL: info
    MAIL_ENCRYPTION: null
    MAIL_FROM_ADDRESS: hello@example.com
    MAIL_FROM_NAME: memoReal
    MAIL_HOST: mailpit
    MAIL_MAILER: smtp
    MAIL_PASSWORD: null
    MAIL_PORT: 1025
    MAIL_USERNAME: null
    MEMCACHED_HOST: 127.0.0.1
    QUEUE_CONNECTION: sync
    REDIS_HOST: 127.0.0.1
    REDIS_PASSWORD: null
    REDIS_PORT: 6379
    SAIL_XDEBUG_MODE: "off"
    SESSION_DRIVER: file
    SESSION_LIFETIME: 120
    VITE_APP_NAME: your-vite-app-name
    VITE_PUSHER_APP_CLUSTER: mt1
    VITE_PUSHER_APP_KEY: your-vite-app-key
    VITE_PUSHER_HOST: vite-pusher.example.com
    VITE_PUSHER_PORT: 6001
    VITE_PUSHER_SCHEME: http
    WWWUSER: "1000"
    XDEBUG_CONFIG: client_host=host.docker.internal
    XDEBUG_MODE: "off"
