apiVersion: v1
kind: Service
metadata:
  name: laravel-test
spec:
  ports:
    - name: "5173"
      port: 5173
      targetPort: 5173
  selector:
    memorial.service: laravel-test
status:
  loadBalancer: {}
