apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: { { .Values.laravel.pvc.name } }
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: { { .Values.laravel.pvc.storage } }
